-- 初始化功能组
INSERT INTO topland.function
    (name)
VALUES ('常用工具.销售报价表.查看'),
       ('常用工具.销售报价表.编辑'),
       ('常用工具.销售报价表.生成合同'),
       ('常用工具.销售报价表.删除'),
       ('客户管理.客户列表.新增客户'),
       ('客户管理.客户列表.查看'),
       ('客户管理.客户列表.编辑'),
       ('客户管理.客户列表.流失&寻回'),
       ('客户管理.客户列表.新增品牌'),
       ('资源管理.器材管理.新增'),
       ('资源管理.器材管理.查看'),
       ('资源管理.器材管理.编辑'),
       ('资源管理.器材管理.删除'),
       ('资源管理.型号管理.新增'),
       ('资源管理.型号管理.编辑'),
       ('资源管理.型号管理.禁用&启用'),
       ('资源管理.仓库管理.新增'),
       ('资源管理.仓库管理.编辑'),
       ('产品管理.产品套餐.新增'),
       ('产品管理.产品套餐.查看'),
       ('产品管理.产品套餐.编辑'),
       ('产品管理.产品套餐.删除'),
       ('产品管理.服务管理.新增'),
       ('产品管理.服务管理.新增子服务'),
       ('产品管理.服务管理.编辑'),
       ('产品管理.服务管理.禁用&启用'),
       ('产品管理.费用管理.新增'),
       ('产品管理.费用管理.编辑'),
       ('产品管理.费用管理.禁用&启用'),
       ('产品管理.费用类型.新增'),
       ('产品管理.费用类型.编辑'),
       ('产品管理.费用类型.禁用&启用'),
       ('异常管理.异常列表.新增'),
       ('异常管理.异常列表.批量新增'),
       ('异常管理.异常列表.查看'),
       ('异常管理.异常列表.编辑'),
       ('异常管理.异常列表.删除'),
       ('异常管理.异常类型.新增'),
       ('异常管理.异常类型.编辑'),
       ('异常管理.异常类型.禁用&启用'),
       ('财务管理.合同录入.新增'),
       ('财务管理.合同录入.查看'),
       ('财务管理.合同录入.关联订单'),
       ('财务管理.合同录入.新增结算'),
       ('财务管理.合同管理.查看'),
       ('财务管理.合同管理.审核'),
       ('财务管理.合同管理.收款'),
       ('财务管理.合同管理.收到纸质合同'),
       ('组织权限.组织管理.同步组织'),
       ('组织权限.组织管理.删除'),
       ('组织权限.角色管理.新增'),
       ('组织权限.角色管理.查看'),
       ('组织权限.角色管理.编辑'),
       ('组织权限.角色管理.删除'),
       ('组织权限.人员管理.授权'),
       ('组织权限.人员管理.批量授权'),
       ('组织权限.人员管理.编辑'),
       ('组织权限.人员管理.同步账号'),
       ('组织权限.人员管理.禁用&启用');

-- 初始化权限
INSERT INTO topland.permission
    (collection, action, permissions, validation, presets, fields)
VALUES ('approval', 'read', '{}', '{}', NULL, '*'),
       ('approval', 'create', '{}', '{}', NULL, '*'),
       ('approval', 'update', '{}', '{}', NULL, '*'),
       ('approval', 'delete', '{}', '{}', NULL, '*'),
       ('attachment', 'create', '{}', '{}', NULL, '*'),
       ('attachment', 'read', '{}', '{}', NULL, '*'),
       ('attachment', 'update', '{}', '{}', NULL, '*'),
       ('attachment', 'delete', '{}', '{}', NULL, '*'),
       ('authority', 'create', '{}', '{}', NULL, '*'),
       ('authority', 'read', '{}', '{}', NULL, '*'),
       ('authority', 'update', '{}', '{}', NULL, '*'),
       ('authority', 'delete', '{}', '{}', NULL, '*'),
       ('brand', 'create', '{}', '{}', NULL, '*'),
       ('brand', 'read', '{}', '{}', NULL, '*'),
       ('brand', 'update', '{}', '{}', NULL, '*'),
       ('brand', 'delete', '{}', '{}', NULL, '*'),
       ('contact', 'create', '{}', '{}', NULL, '*'),
       ('contact', 'read', '{}', '{}', NULL, '*'),
       ('contact', 'update', '{}', '{}', NULL, '*'),
       ('contact', 'delete', '{}', '{}', NULL, '*'),
       ('contract', 'read', '{}', '{}', NULL, '*'),
       ('contract', 'create', '{}', '{}', NULL, '*'),
       ('contract', 'update', '{}', '{}', NULL, '*'),
       ('contract', 'delete', '{}', '{}', NULL, '*'),
       ('cost', 'create', '{}', '{}', NULL, '*'),
       ('cost', 'update', '{}', '{}', NULL, '*'),
       ('cost', 'read', '{}', '{}', NULL, '*'),
       ('cost', 'delete', '{}', '{}', NULL, '*'),
       ('cost_type', 'create', '{}', '{}', NULL, '*'),
       ('cost_type', 'update', '{}', '{}', NULL, '*'),
       ('cost_type', 'read', '{}', '{}', NULL, '*'),
       ('cost_type', 'delete', '{}', '{}', NULL, '*'),
       ('customer', 'create', '{}', '{}', NULL, '*'),
       ('customer', 'update', '{}', '{}', NULL, '*'),
       ('customer', 'read', '{}', '{}', NULL, '*'),
       ('customer', 'delete', '{}', '{}', NULL, '*'),
       ('department', 'create', '{}', '{}', NULL, '*'),
       ('department', 'update', '{}', '{}', NULL, '*'),
       ('department', 'read', '{}', '{}', NULL, '*'),
       ('department', 'delete', '{}', '{}', NULL, '*'),
       ('equipment', 'create', '{}', '{}', NULL, '*'),
       ('equipment', 'read', '{}', '{}', NULL, '*'),
       ('equipment', 'update', '{}', '{}', NULL, '*'),
       ('equipment', 'delete', '{}', '{}', NULL, '*'),
       ('exception_type', 'create', '{}', '{}', NULL, '*'),
       ('exception_type', 'update', '{}', '{}', NULL, '*'),
       ('exception_type', 'read', '{}', '{}', NULL, '*'),
       ('exception_type', 'delete', '{}', '{}', NULL, '*'),
       ('invoice', 'create', '{}', '{}', NULL, '*'),
       ('invoice', 'read', '{}', '{}', NULL, '*'),
       ('invoice', 'delete', '{}', '{}', NULL, '*'),
       ('invoice', 'update', '{}', '{}', NULL, '*'),
       ('model', 'create', '{}', '{}', NULL, '*'),
       ('model', 'read', '{}', '{}', NULL, '*'),
       ('model', 'update', '{}', '{}', NULL, '*'),
       ('model', 'delete', '{}', '{}', NULL, '*'),
       ('operation', 'read', '{}', '{}', NULL, '*'),
       ('operation', 'create', '{}', '{}', NULL, '*'),
       ('operation', 'update', '{}', '{}', NULL, '*'),
       ('operation', 'delete', '{}', '{}', NULL, '*'),
       ('order', 'create', '{}', '{}', NULL, '*'),
       ('order', 'update', '{}', '{}', NULL, '*'),
       ('order', 'read', '{}', '{}', NULL, '*'),
       ('order', 'delete', '{}', '{}', NULL, '*'),
       ('package', 'create', '{}', '{}', NULL, '*'),
       ('package', 'update', '{}', '{}', NULL, '*'),
       ('package', 'delete', '{}', '{}', NULL, '*'),
       ('package', 'read', '{}', '{}', NULL, '*'),
       ('package_service', 'read', '{}', '{}', NULL, '*'),
       ('package_service', 'create', '{}', '{}', NULL, '*'),
       ('package_service', 'update', '{}', '{}', NULL, '*'),
       ('package_service', 'delete', '{}', '{}', NULL, '*'),
       ('packages_services', 'create', '{}', '{}', NULL, '*'),
       ('packages_services', 'read', '{}', '{}', NULL, '*'),
       ('packages_services', 'update', '{}', '{}', NULL, '*'),
       ('packages_services', 'delete', '{}', '{}', NULL, '*'),
       ('permission', 'create', '{}', '{}', NULL, '*'),
       ('permission', 'update', '{}', '{}', NULL, '*'),
       ('permission', 'read', '{}', '{}', NULL, '*'),
       ('permission', 'delete', '{}', '{}', NULL, '*'),
       ('quotation', 'create', '{}', '{}', NULL, '*'),
       ('quotation', 'update', '{}', '{}', NULL, '*'),
       ('quotation', 'read', '{}', '{}', NULL, '*'),
       ('quotation', 'delete', '{}', '{}', NULL, '*'),
       ('quotation_service', 'create', '{}', '{}', NULL, '*'),
       ('quotation_service', 'update', '{}', '{}', NULL, '*'),
       ('quotation_service', 'read', '{}', '{}', NULL, '*'),
       ('quotation_service', 'delete', '{}', '{}', NULL, '*'),
       ('receive', 'create', '{}', '{}', NULL, '*'),
       ('receive', 'update', '{}', '{}', NULL, '*'),
       ('receive', 'read', '{}', '{}', NULL, '*'),
       ('receive', 'delete', '{}', '{}', NULL, '*'),
       ('service', 'create', '{}', '{}', NULL, '*'),
       ('service', 'update', '{}', '{}', NULL, '*'),
       ('service', 'read', '{}', '{}', NULL, '*'),
       ('service', 'delete', '{}', '{}', NULL, '*'),
       ('services_costs', 'create', '{}', '{}', NULL, '*'),
       ('services_costs', 'update', '{}', '{}', NULL, '*'),
       ('services_costs', 'read', '{}', '{}', NULL, '*'),
       ('services_costs', 'delete', '{}', '{}', NULL, '*'),
       ('settlement_contract', 'read', '{}', '{}', NULL, '*'),
       ('settlement_contract', 'create', '{}', '{}', NULL, '*'),
       ('settlement_contract', 'update', '{}', '{}', NULL, '*'),
       ('settlement_contract', 'delete', '{}', '{}', NULL, '*'),
       ('storage', 'create', '{}', '{}', NULL, '*'),
       ('storage', 'update', '{}', '{}', NULL, '*'),
       ('storage', 'read', '{}', '{}', NULL, '*'),
       ('storage', 'delete', '{}', '{}', NULL, '*'),
       ('user', 'create', '{}', '{}', NULL, '*'),
       ('user', 'update', '{}', '{}', NULL, '*'),
       ('user', 'read', '{}', '{}', NULL, '*'),
       ('user', 'delete', '{}', '{}', NULL, '*'),
       ('users_departments', 'create', '{}', '{}', NULL, '*'),
       ('users_departments', 'read', '{}', '{}', NULL, '*'),
       ('users_departments', 'update', '{}', '{}', NULL, '*'),
       ('users_departments', 'delete', '{}', '{}', NULL, '*'),
       ('directus_files', 'create', '{}', '{}', NULL, '*'),
       ('directus_files', 'update', '{}', '{}', NULL, '*'),
       ('directus_files', 'read', '{}', '{}', NULL, '*'),
       ('directus_files', 'delete', '{}', '{}', NULL, '*'),
       ('directus_folders', 'create', '{}', '{}', NULL, '*'),
       ('directus_folders', 'read', '{}', '{}', NULL, '*'),
       ('directus_folders', 'update', '{}', '{}', NULL, '*'),
       ('directus_folders', 'delete', '{}', '{}', NULL, '*'),
       ('directus_permissions', 'create', '{}', '{}', NULL, '*'),
       ('directus_permissions', 'read', '{}', '{}', NULL, '*'),
       ('directus_permissions', 'update', '{}', '{}', NULL, '*'),
       ('directus_permissions', 'delete', '{}', '{}', NULL, '*'),
       ('directus_roles', 'create', '{}', '{}', NULL, '*'),
       ('directus_roles', 'read', '{}', '{}', NULL, '*'),
       ('directus_roles', 'update', '{}', '{}', NULL, '*'),
       ('directus_roles', 'delete', '{}', '{}', NULL, '*'),
       ('directus_users', 'create', '{}', '{}', NULL, '*'),
       ('directus_users', 'update', '{}', '{}', NULL, '*'),
       ('directus_users', 'read', '{}', '{}', NULL, '*'),
       ('directus_users', 'delete', '{}', '{}', NULL, '*');